### ISSUE TITLE
Invalid e-mail

### ISSUE THREAD

**Issue by ogirginc** [andrewmcodes/ruby-meetup-online#16]
# Bug Report

## Describe the bug

Can't register with my e-mail address `ogirginc@ogirginc.com` (google)

## Steps To Reproduce

Try `ogirginc@ogirginc.com`

### Screenshots

![Screenshot 2020-03-11 at 10 11 13](https://user-images.githubusercontent.com/7466873/76391594-db093980-6380-11ea-9964-966b3dca51dd.png)

### Desktop

- macOS
- FF Developer Edition

**Comment by andrewmcodes** [comment]
hm, weird. I added you to the list manually if that's ok, @ogirginc! Not really sure why Mailchimp decided to flag it.

**Comment by ogirginc** [comment]
I thought it was a front-end issue. Thanks!

**Comment by andrewmcodes** [comment]
The message displayed in the banner is whatever Mailchimp replied to the request with. So in this instance, it sent back the result as an error, and the message as what you see above. 🙂
