### ISSUE TITLE
Text not visible

### ISSUE THREAD

**Issue by websebdev** [andrewmcodes/ruby-meetup-online#19]
# Bug Report

## Describe the bug

The "Help us spread the word!" text above share buttons section (twitter, linked in etc) is white, the same color as the background, which makes the text not visible. Same thing with the ad above "Are you interested in online Ruby Meetups?" box.

However, on my phone the text shows properly since I use chrome's dark mode and it changes the background color to dark blue.

## Expected behavior

The text should not be the same color as the background.

## Steps To Reproduce

Disable dark mode if you have it on, go to https://rubymeetup.online/ and scroll down to the share buttons. 

### Screenshots

![Selection_016](https://user-images.githubusercontent.com/23641464/76707726-1d57b100-66c8-11ea-87c2-4d3f477870e0.png)

With selected text:
![Selection_017](https://user-images.githubusercontent.com/23641464/76707727-1df04780-66c8-11ea-94e1-71478ec72af1.png)

### Desktop

- OS: Ubuntu 18.04
- Browser: Chrome Version 80.0.3987.132 (Official Build) (64-bit)

**Comment by andrewmcodes** [comment]
Ah good catch - I'll get that fixed in the morning.

**Comment by andrewmcodes** [comment]
Fixed - thanks @seb1441
