### ISSUE TITLE
Error message when already subscribed shows link in html

### ISSUE THREAD

**Issue by claracodes** [andrewmcodes/ruby-meetup-online#22]
# Bug Report

## Describe the bug

When I tried to submit my email I got a message that I am already subscribed. The link in this message is not rendered correctly.

## Expected behavior

The link should be clickable.

## Steps To Reproduce

Try to sign up which an email that is already subscribed.

### Screenshots

<img width="1357" alt="Screenshot 2020-04-03 at 10 07 59" src="https://user-images.githubusercontent.com/29435293/78387033-76ae5400-7593-11ea-9d5b-539ab33168ed.png">

### Desktop

- OS: MacOS 10.15.4
- Browser: firefox

**Comment by andrewmcodes** [comment]
@claracodes thanks so much for letting me know!
